"""
Django settings for sastreria project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import dj_database_url
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'your-secure-secret-key')

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'
DEBUG = False

ALLOWED_HOSTS = ['fortiumtailor.com', 'www.fortiumtailor.com']

CSRF_TRUSTED_ORIGINS = [
    'https://fortiumtailor.com',
    'https://www.fortiumtailor.com',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'misastreria',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'misastreria.middleware.CajaAbiertaMiddleware',
]

ROOT_URLCONF = 'sastreria.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'misastreria.context_processors.caja_sesion',
            ],
        },
    },
]

# Configuración de autenticación
LOGIN_URL = '/sistema/login/'
LOGIN_REDIRECT_URL = '/sistema/dashboard/'
LOGOUT_REDIRECT_URL = '/'

WSGI_APPLICATION = 'sastreria.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Configuración condicional para la base de datos
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME', 'cpanelusr_db'),
        'USER': os.environ.get('DB_USER', 'cpanelusr_user'),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/La_Paz'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
FORCE_SCRIPT_NAME = '/sistema'

STATIC_URL = '/sistema/static/'
STATICFILES_DIRS = []
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Django 5.1 eliminó STATICFILES_STORAGE en favor de STORAGES. Mientras estuvo
# como STATICFILES_STORAGE, esta línea no hacía nada y se servían los archivos
# sin comprimir y sin hash: cada cambio en un .js o .css quedaba tapado por el
# caché del navegador, porque la URL seguía siendo la misma.
#
# Con el backend de whitenoise, el nombre del archivo lleva un hash de su
# contenido (etiquetas.c529a151fca0.js). Al cambiar el archivo cambia la URL, y
# el navegador se ve obligado a pedirlo de nuevo. También deja los .gz y .br
# pregenerados al momento de recolectar, en vez de comprimir en cada request.
#
# A cambio, `collectstatic` pasa a ser obligatorio en cada despliegue que toque
# algo de static/: hasta que corra, las plantillas siguen apuntando al hash
# anterior.
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/sistema/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
