from django.urls import path
from . import views, views_etiquetas
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import RedirectView

urlpatterns = [
    # Redirige la URL base del sistema a la página de login
    path('', RedirectView.as_view(pattern_name='login', permanent=False), name='index'),

    # Login y Logout
    path('login/', LoginView.as_view(template_name='misastreria/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    # Dashboard
    path('dashboard/', views.dashboard, name='dashboard'),
    # Empleados
    path('empleados/', views.lista_empleados, name='lista_empleados'),
    path('empleados/crear/', views.crear_empleado, name='crear_empleado'),
    path('empleados/editar/<int:id>/', views.editar_empleado, name='editar_empleado'),
    path('empleados/eliminar/<int:id>/', views.eliminar_empleado, name='eliminar_empleado'),
    path('empleados/<int:id>/detalle/', views.detalle_empleado, name='detalle_empleado'),
    path('empleados/<int:id>/devengaciones/excel/', views.exportar_devengaciones_empleado_excel, name='exportar_devengaciones_empleado_excel'),
    path('empleados/permiso/<int:empleado_id>/', views.crear_permiso, name='crear_permiso'),
    path('empleados/falta/<int:empleado_id>/', views.crear_falta, name='crear_falta'),
    path('empleados/permiso/eliminar/<int:id>/', views.eliminar_permiso, name='eliminar_permiso'),
    path('empleados/falta/eliminar/<int:id>/', views.eliminar_falta, name='eliminar_falta'),
    path('empleados/<int:empleado_id>/comision/pagar/', views.pagar_comision_empleado, name='pagar_comision_empleado'),
    path('empleados/reporte/dias_trabajados/', views.reporte_dias_trabajados, name='reporte_dias_trabajados'),
    # Clientes
    path('clientes/', views.lista_clientes, name='lista_clientes'),
    path('clientes/buscar/', views.buscar_clientes, name='buscar_clientes'),
    path('empleados/buscar/', views.buscar_empleados, name='buscar_empleados'),
    path('clientes/crear/', views.crear_cliente, name='crear_cliente'),
    path('clientes/editar/<int:id>/', views.editar_cliente, name='editar_cliente'),
    path('clientes/eliminar/<int:id>/', views.eliminar_cliente, name='eliminar_cliente'),
    path('clientes/<int:id>/historial/', views.historial_cliente, name='historial_cliente'),
    # Tipos dinámicos
    path('tipos/prenda/buscar/', views.buscar_tipo_prenda, name='buscar_tipo_prenda'),
    path('tipos/prenda/crear/', views.crear_tipo_prenda, name='crear_tipo_prenda'),
    path('tipos/reparacion/buscar/', views.buscar_tipo_reparacion, name='buscar_tipo_reparacion'),
    path('tipos/reparacion/crear/', views.crear_tipo_reparacion, name='crear_tipo_reparacion'),
    path('tipos/estado-alquiler/buscar/', views.buscar_estado_alquiler, name='buscar_estado_alquiler'),
    path('tipos/estado-alquiler/crear/', views.crear_estado_alquiler, name='crear_estado_alquiler'),
    path('tipos/unidad-medida/buscar/', views.buscar_unidad_medida, name='buscar_unidad_medida'),
    path('tipos/unidad-medida/crear/', views.crear_unidad_medida, name='crear_unidad_medida'),
    path('tipos/tipo-contrato/buscar/', views.buscar_tipo_contrato, name='buscar_tipo_contrato'),
    path('tipos/tipo-contrato/crear/', views.crear_tipo_contrato, name='crear_tipo_contrato'),
    path('tipos/tipo-material/buscar/', views.buscar_tipo_material, name='buscar_tipo_material'),
    path('tipos/tipo-material/crear/', views.crear_tipo_material, name='crear_tipo_material'),
    path('tipos/ubicacion-item/buscar/', views.buscar_ubicacion_item, name='buscar_ubicacion_item'),
    path('tipos/ubicacion-item/crear/', views.crear_ubicacion_item, name='crear_ubicacion_item'),
    path('inventario/buscar/', views.buscar_prenda_inventario, name='buscar_prenda_inventario'),
    path('confecciones/buscar/', views.buscar_confeccion, name='buscar_confeccion'),
    path('confecciones/modelos/buscar/', views.buscar_modelo_confeccion, name='buscar_modelo_confeccion'),
    path('confecciones/modelos/crear/', views.crear_modelo_confeccion, name='crear_modelo_confeccion'),
    # Reparaciones
    path('reparaciones/', views.lista_reparaciones, name='lista_reparaciones'),
    path('reparaciones/crear/', views.crear_reparacion, name='crear_reparacion'),
    path('reparaciones/editar/<int:id>/', views.editar_reparacion, name='editar_reparacion'),
    path('reparaciones/eliminar/<int:id>/', views.eliminar_reparacion, name='eliminar_reparacion'),
    path('reparaciones/recibo_reparacion/<int:id>/', views.exportar_recibo_reparacion_pdf, name='exportar_recibo_reparacion_pdf'),
    path('reparaciones/etiqueta/<int:id>/', views_etiquetas.etiqueta_reparacion_pdf, name='exportar_etiqueta_reparacion_pdf'),
    path('reparaciones/detalle/<int:id>/', views.detalle_reparacion, name='detalle_reparacion'),
    path('reparaciones/en-proceso/<int:id>/', views.reparacion_en_proceso, name='reparacion_en_proceso'),
    path('reparaciones/entregado/<int:id>/', views.marcar_entregado, name='marcar_entregado'),
    path('reparaciones/<int:id>/pago/', views.agregar_pago_reparacion, name='agregar_pago_reparacion'),
    # Ventas
    path('ventas/', views.lista_ventas, name='lista_ventas'),
    path('ventas/crear/', views.crear_venta, name='crear_venta'),
    path('ventas/editar/<int:id>/', views.editar_venta, name='editar_venta'),
    path('ventas/eliminar/<int:id>/', views.eliminar_venta, name='eliminar_venta'),
    path('ventas/detalle/<int:id>/', views.detalle_venta, name='detalle_venta'),
    path('ventas/<int:id>/pago/', views.agregar_pago_venta, name='agregar_pago_venta'),
    path('ventas/recibo/<int:id>/', views.exportar_recibo_pdf, name='exportar_recibo_pdf'),
    path('ventas/get_precio_articulo/', views.get_precio_articulo, name='get_precio_articulo'),
    # Confecciones
    path('confecciones/', views.lista_confecciones, name='lista_confecciones'),
    path('confecciones/crear/', views.crear_confeccion, name='crear_confeccion'),
    path('confecciones/editar/<int:id>/', views.editar_confeccion, name='editar_confeccion'),
    path('confecciones/eliminar/<int:id>/', views.eliminar_confeccion, name='eliminar_confeccion'),
    path('confecciones/en-proceso/<int:id>/', views.confeccion_en_proceso, name='confeccion_en_proceso'),
    path('confecciones/entregar/<int:id>/', views.entregar_confeccion, name='entregar_confeccion'),
    path('confecciones/recibo/<int:id>/', views.exportar_recibo_confeccion_pdf, name='exportar_recibo_confeccion_pdf'),
    path('confecciones/etiqueta/<int:id>/', views_etiquetas.etiqueta_confeccion_pdf, name='exportar_etiqueta_confeccion_pdf'),
    path('confecciones/detalle/<int:id>/', views.detalle_confeccion, name='detalle_confeccion'),
    path('confecciones/<int:id>/pago/', views.agregar_pago_confeccion, name='agregar_pago_confeccion'),
    # Alquileres
    path('alquileres/', views.lista_alquileres, name='lista_alquileres'),
    path('alquileres/crear/', views.crear_alquiler, name='crear_alquiler'),
    path('alquileres/editar/<int:id>/', views.editar_alquiler, name='editar_alquiler'),
    path('alquileres/eliminar/<int:id>/', views.eliminar_alquiler, name='eliminar_alquiler'),
    path('alquileres/devolver/<int:id>/', views.devolver_alquiler, name='devolver_alquiler'),
    path('alquileres/confirmar/<int:id>/', views.confirmar_reserva, name='confirmar_reserva'),
    path('alquileres/comprobante/pdf/<int:id>/', views.exportar_comprobante_alquiler_pdf, name='exportar_comprobante_alquiler_pdf'),
    path('alquileres/detalle/<int:id>/', views.detalle_alquiler, name='detalle_alquiler'),
    path('alquileres/<int:id>/pago/', views.agregar_pago_alquiler, name='agregar_pago_alquiler'),
    path('alquileres/<int:id>/recargo/', views.agregar_recargo_alquiler, name='agregar_recargo_alquiler'),
    # Prendas
    path('prendas/', views.lista_prendas, name='lista_prendas'),
    path('prendas/crear/', views.crear_prenda, name='crear_prenda'),
    path('prendas/items-proximos-baja/', views.items_proximos_baja, name='items_proximos_baja'),
    path('prendas/editar/<int:id>/', views.editar_prenda, name='editar_prenda'),
    path('prendas/eliminar/<int:id>/', views.eliminar_prenda, name='eliminar_prenda'),
    path('prendas/items/<int:id>/editar/', views.editar_prenda_item, name='editar_prenda_item'),
    path('prendas/items/<int:id>/baja/', views.baja_prenda_item, name='baja_prenda_item'),
    path('prendas/items/buscar/', views.buscar_prenda_items, name='buscar_prenda_items'),
    path('prendas/<int:id>/agregar/', views.agregar_items_prenda, name='agregar_items_prenda'),
    path('prendas/<int:id>/detalle/', views.detalle_prenda, name='detalle_prenda'),
    path('prendas/items/<int:id>/etiqueta/', views_etiquetas.etiqueta_item_pdf, name='exportar_etiqueta_item_pdf'),
    path('prendas/<int:id>/etiquetas/', views_etiquetas.etiquetas_prenda_pdf, name='exportar_etiquetas_prenda_pdf'),
    # Etiquetas — calibración contra el rollo físico
    path('etiquetas/calibrar/', views_etiquetas.calibrar, name='etiquetas_calibrar'),
    path('etiquetas/calibrar/muestra/', views_etiquetas.etiqueta_demo_pdf, name='exportar_etiqueta_demo_pdf'),
    path('etiquetas/calibrar/impresora/', views_etiquetas.fijar_impresora, name='etiquetas_set_impresora'),
    path('etiquetas/calibrar/zpl/', views_etiquetas.zpl_calibracion, name='etiquetas_zpl_calibracion'),
    # Etiquetas — diseñador de plantillas
    path('etiquetas/', views_etiquetas.lista_plantillas, name='lista_plantillas'),
    path('etiquetas/disenador/', views_etiquetas.disenador, name='disenador_etiqueta'),
    path('etiquetas/disenador/<int:id>/', views_etiquetas.disenador, name='editar_plantilla'),
    path('etiquetas/guardar/', views_etiquetas.guardar_plantilla, name='guardar_plantilla'),
    path('etiquetas/guardar/<int:id>/', views_etiquetas.guardar_plantilla, name='actualizar_plantilla'),
    path('etiquetas/eliminar/<int:id>/', views_etiquetas.eliminar_plantilla, name='eliminar_plantilla'),
    path('etiquetas/items/', views_etiquetas.buscar_items, name='buscar_items_etiqueta'),
    path('etiquetas/simbolo/<str:clave>.png', views_etiquetas.simbolo_png, name='simbolo_etiqueta'),
    path('etiquetas/previsualizar/', views_etiquetas.previsualizar_pdf, name='previsualizar_etiqueta'),
    path('etiquetas/zpl/', views_etiquetas.previsualizar_zpl, name='zpl_etiqueta'),
    path('etiquetas/zpl/descargar/', views_etiquetas.descargar_zpl, name='descargar_zpl_etiqueta'),
    path('etiquetas/imprimir/', views_etiquetas.imprimir, name='imprimir_etiqueta'),
    # Insumos
    path('insumos/', views.lista_insumos, name='lista_insumos'),
    path('insumos/crear/', views.crear_insumo, name='crear_insumo'),
    path('insumos/editar/<int:id>/', views.editar_insumo, name='editar_insumo'),
    path('insumos/eliminar/<int:id>/', views.eliminar_insumo, name='eliminar_insumo'),
    # Producción
    path('produccion/', views.lista_ordenes, name='lista_ordenes'),
    path('produccion/crear/', views.crear_orden, name='crear_orden'),
    path('produccion/editar/<int:id>/', views.editar_orden, name='editar_orden'),
    path('produccion/eliminar/<int:id>/', views.eliminar_orden, name='eliminar_orden'),
    path('produccion/avanzar/<int:id>/', views.avanzar_estado_orden, name='avanzar_estado_orden'),
    # Transacciones
    path('transacciones/', views.lista_transacciones, name='lista_transacciones'),
    path('transacciones/crear/', views.crear_transaccion, name='crear_transaccion'),
    path('transacciones/editar/<int:id>/', views.editar_transaccion, name='editar_transaccion'),
    path('transacciones/eliminar/<int:id>/', views.eliminar_transaccion, name='eliminar_transaccion'),
    # Reportes
    path('reportes/empleados/', views.reporte_empleados, name='reporte_empleados'),
    path('reportes/empleados/pdf/', views.exportar_empleados_pdf, name='exportar_empleados_pdf'),
    path('reportes/empleados/excel/', views.exportar_empleados_excel, name='exportar_empleados_excel'),
    path('reportes/clientes/', views.reporte_clientes, name='reporte_clientes'),
    path('reportes/reparaciones/', views.reporte_reparaciones, name='reporte_reparaciones'),
    path('reportes/reparaciones/pdf/', views.exportar_reparaciones_pdf, name='exportar_reparaciones_pdf'),
    path('reportes/reparaciones/excel/', views.exportar_reparaciones_excel, name='exportar_reparaciones_excel'),
    path('reportes/ventas/', views.reporte_ventas, name='reporte_ventas'),
    path('reportes/confecciones/', views.reporte_confecciones, name='reporte_confecciones'),
    path('reportes/alquileres/', views.reporte_alquileres, name='reporte_alquileres'),
    path('reportes/transacciones/', views.reporte_transacciones, name='reporte_transacciones'),
    path('reportes/inventario/', views.reporte_inventario, name='reporte_inventario'),
    path('reportes/articulos/', views.reporte_articulos, name='reporte_articulos'),
    path('reportes/stock/', views.reporte_stock, name='reporte_stock'),
    path('reportes/ingresos/', views.reporte_ingresos, name='reporte_ingresos'),
    # Kardex
    path('kardex/item/<str:codigo_item>/',     views.kardex_item,        name='kardex_item'),
    path('kardex/inventario/<int:prenda_id>/', views.kardex_inventario,  name='kardex_inventario'),
    path('kardex/financiero/',                 views.kardex_financiero,  name='kardex_financiero'),
    # Caja — movimientos
    path('caja/movimientos/', views.lista_movimientos_caja, name='lista_movimientos_caja'),
    path('caja/movimientos/crear/', views.crear_movimiento_caja, name='crear_movimiento_caja'),
    path('caja/movimientos/<int:pk>/', views.detalle_movimiento_caja, name='detalle_movimiento_caja'),
    path('caja/movimientos/<int:pk>/revertir/', views.revertir_movimiento_caja, name='revertir_movimiento_caja'),
    # Caja — sesiones
    path('caja/sesiones/', views.lista_sesiones_caja, name='lista_sesiones_caja'),
    path('caja/sesiones/abrir/', views.abrir_sesion_caja, name='abrir_sesion_caja'),
    path('caja/sesiones/<int:pk>/', views.detalle_sesion_caja, name='detalle_sesion_caja'),
    path('caja/sesiones/<int:pk>/excel/', views.export_detalle_sesion_excel, name='export_detalle_sesion_excel'),
    path('caja/sesiones/<int:pk>/cerrar/', views.cerrar_sesion_caja, name='cerrar_sesion_caja'),
    # Caja — resumen y exports
    path('caja/resumen/', views.resumen_caja, name='resumen_caja'),
    path('caja/resumen/pdf/', views.export_resumen_caja_pdf, name='export_resumen_caja_pdf'),
    path('caja/resumen/excel/', views.export_resumen_caja_excel, name='export_resumen_caja_excel'),
    # Caja — conceptos de gasto
    path('caja/conceptos/', views.lista_tipo_gasto, name='lista_tipo_gasto'),
    path('caja/conceptos/crear/', views.crear_tipo_gasto, name='crear_tipo_gasto'),
    path('caja/conceptos/<int:pk>/editar/', views.editar_tipo_gasto, name='editar_tipo_gasto'),
    path('caja/conceptos/<int:pk>/eliminar/', views.eliminar_tipo_gasto, name='eliminar_tipo_gasto'),
    # Gastos varios (alias for Transaccion — rebrand, no DB changes)
    path('gastos-varios/', views.lista_transacciones, name='lista_gastos_varios'),
    path('gastos-varios/crear/', views.crear_transaccion, name='crear_gasto_varios'),
    path('gastos-varios/<int:id>/editar/', views.editar_transaccion, name='editar_gasto_varios'),
    path('gastos-varios/<int:id>/eliminar/', views.eliminar_transaccion, name='eliminar_gasto_varios'),
    # Conjuntos
    path('conjuntos/', views.lista_conjuntos, name='lista_conjuntos'),
    path('conjuntos/crear/', views.crear_conjunto, name='crear_conjunto'),
    path('conjuntos/<int:pk>/editar/', views.editar_conjunto, name='editar_conjunto'),
    path('conjuntos/<int:pk>/eliminar/', views.eliminar_conjunto, name='eliminar_conjunto'),
    # Analítica - Fase 2
    path('analitica/items/', views.analitica_items, name='analitica_items'),
    path('analitica/empleados/', views.analitica_empleados, name='analitica_empleados'),
    path('analitica/clientes-ltv/', views.analitica_clientes_ltv, name='analitica_clientes_ltv'),
    path('analitica/operativas/', views.analitica_operativas, name='analitica_operativas'),
    path('analitica/comparativas/', views.analitica_comparativas, name='analitica_comparativas'),
    path('analitica/estacionalidad/', views.estacionalidad, name='analitica_estacionalidad'),
    path('analitica/prendas-temporada/', views.prendas_temporada, name='analitica_prendas_temporada'),
]