# Generated by Django 5.2 on 2025-07-07 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misastreria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
    ]
