# Generated by Django 5.2 on 2026-04-26 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misastreria', '0002_alter_cliente_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ci',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='CI'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='ci',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='CI'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=100, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='edad',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad'),
        ),
    ]
