# Generated by Django 5.2 on 2026-04-27 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misastreria', '0004_alter_empleado_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confeccion',
            name='chaleco_altura_botones',
        ),
        migrations.RemoveField(
            model_name='confeccion',
            name='chaleco_contorno_busto',
        ),
        migrations.RemoveField(
            model_name='confeccion',
            name='chaleco_contorno_cadera',
        ),
        migrations.RemoveField(
            model_name='confeccion',
            name='chaleco_contorno_cintura',
        ),
        migrations.RemoveField(
            model_name='confeccion',
            name='chaleco_largo_talle',
        ),
        migrations.RemoveField(
            model_name='confeccion',
            name='chaleco_largo_total',
        ),
        migrations.RemoveField(
            model_name='confeccion',
            name='chaleco_mujer_altura_busto',
        ),
        migrations.RemoveField(
            model_name='confeccion',
            name='chaleco_mujer_contorno_busto',
        ),
        migrations.RemoveField(
            model_name='confeccion',
            name='chaleco_mujer_contorno_cadera',
        ),
        migrations.RemoveField(
            model_name='confeccion',
            name='chaleco_mujer_contorno_cintura',
        ),
        migrations.RemoveField(
            model_name='confeccion',
            name='chaleco_mujer_largo_delantero',
        ),
        migrations.RemoveField(
            model_name='confeccion',
            name='chaleco_mujer_largo_talle',
        ),
        migrations.RemoveField(
            model_name='confeccion',
            name='chaleco_mujer_largo_total',
        ),
        migrations.RemoveField(
            model_name='confeccion',
            name='chaleco_mujer_separacion_busto',
        ),
        migrations.RemoveField(
            model_name='confeccion',
            name='pantalon_contorno_bota',
        ),
        migrations.RemoveField(
            model_name='confeccion',
            name='pantalon_contorno_cadera',
        ),
        migrations.RemoveField(
            model_name='confeccion',
            name='pantalon_contorno_cintura',
        ),
        migrations.RemoveField(
            model_name='confeccion',
            name='pantalon_contorno_pierna',
        ),
        migrations.RemoveField(
            model_name='confeccion',
            name='pantalon_contorno_rodilla',
        ),
        migrations.RemoveField(
            model_name='confeccion',
            name='pantalon_largo_entrepierna',
        ),
        migrations.RemoveField(
            model_name='confeccion',
            name='pantalon_largo_total',
        ),
        migrations.RemoveField(
            model_name='confeccion',
            name='pantalon_tiro_delantero',
        ),
        migrations.RemoveField(
            model_name='confeccion',
            name='pantalon_tiro_trasero',
        ),
        migrations.RemoveField(
            model_name='confeccion',
            name='saco_ancho_espalda',
        ),
        migrations.RemoveField(
            model_name='confeccion',
            name='saco_ancho_hombros',
        ),
        migrations.RemoveField(
            model_name='confeccion',
            name='saco_contorno_brazo',
        ),
        migrations.RemoveField(
            model_name='confeccion',
            name='saco_contorno_busto',
        ),
        migrations.RemoveField(
            model_name='confeccion',
            name='saco_contorno_cadera',
        ),
        migrations.RemoveField(
            model_name='confeccion',
            name='saco_contorno_cintura',
        ),
        migrations.RemoveField(
            model_name='confeccion',
            name='saco_contorno_puno',
        ),
        migrations.RemoveField(
            model_name='confeccion',
            name='saco_largo_manga',
        ),
        migrations.RemoveField(
            model_name='confeccion',
            name='saco_largo_talle',
        ),
        migrations.RemoveField(
            model_name='confeccion',
            name='saco_largo_total',
        ),
        migrations.RemoveField(
            model_name='confeccion',
            name='saco_mujer_altura_busto',
        ),
        migrations.RemoveField(
            model_name='confeccion',
            name='saco_mujer_ancho_espalda',
        ),
        migrations.RemoveField(
            model_name='confeccion',
            name='saco_mujer_ancho_hombros',
        ),
        migrations.RemoveField(
            model_name='confeccion',
            name='saco_mujer_contorno_busto',
        ),
        migrations.RemoveField(
            model_name='confeccion',
            name='saco_mujer_contorno_cadera',
        ),
        migrations.RemoveField(
            model_name='confeccion',
            name='saco_mujer_contorno_cintura',
        ),
        migrations.RemoveField(
            model_name='confeccion',
            name='saco_mujer_dif_talle',
        ),
        migrations.RemoveField(
            model_name='confeccion',
            name='saco_mujer_largo_talle',
        ),
        migrations.RemoveField(
            model_name='confeccion',
            name='saco_mujer_largo_total',
        ),
        migrations.RemoveField(
            model_name='confeccion',
            name='saco_mujer_separacion_busto',
        ),
        migrations.RemoveField(
            model_name='confeccion',
            name='tipo_prenda',
        ),
        migrations.AlterField(
            model_name='confeccion',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='reparacion',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='Código'),
        ),
        migrations.CreateModel(
            name='ConfeccionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_prenda', models.CharField(choices=[('pantalon', 'Pantalón'), ('chaleco', 'Chaleco'), ('saco', 'Saco'), ('saco_mujer', 'Saco – Mujer'), ('chaleco_mujer', 'Chaleco – Mujer')], max_length=20)),
                ('pantalon_largo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pantalon_contorno_cintura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pantalon_contorno_cadera', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pantalon_largo_entrepierna', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pantalon_contorno_pierna', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pantalon_contorno_rodilla', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pantalon_contorno_bota', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pantalon_tiro_delantero', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pantalon_tiro_trasero', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('chaleco_contorno_busto', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('chaleco_contorno_cintura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('chaleco_contorno_cadera', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('chaleco_largo_talle', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('chaleco_largo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('chaleco_altura_botones', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('saco_contorno_busto', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('saco_contorno_cintura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('saco_contorno_cadera', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('saco_largo_talle', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('saco_largo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('saco_ancho_hombros', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('saco_ancho_espalda', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('saco_contorno_brazo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('saco_largo_manga', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('saco_contorno_puno', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('saco_mujer_contorno_busto', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('saco_mujer_contorno_cintura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('saco_mujer_contorno_cadera', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('saco_mujer_ancho_hombros', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('saco_mujer_ancho_espalda', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('saco_mujer_largo_talle', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('saco_mujer_largo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('saco_mujer_altura_busto', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('saco_mujer_separacion_busto', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('saco_mujer_dif_talle', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('chaleco_mujer_contorno_busto', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('chaleco_mujer_contorno_cintura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('chaleco_mujer_contorno_cadera', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('chaleco_mujer_largo_talle', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('chaleco_mujer_largo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('chaleco_mujer_altura_busto', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('chaleco_mujer_separacion_busto', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('chaleco_mujer_largo_delantero', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('confeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='misastreria.confeccion')),
            ],
        ),
    ]
