# Generated by Django 5.2 on 2026-04-27 23:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misastreria', '0006_add_creado_to_cliente_confeccion_transaccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Código')),
                ('tipo_material', models.CharField(choices=[('tela', 'Tela'), ('hilo', 'Hilo'), ('accesorio', 'Accesorio'), ('entretela', 'Entretela'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo de Material')),
                ('articulo', models.CharField(max_length=100, verbose_name='Artículo')),
                ('coleccion', models.CharField(blank=True, max_length=100, verbose_name='Colección / Cuaderno')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Color')),
                ('codigo_referencia', models.CharField(blank=True, max_length=100, verbose_name='Código de Referencia')),
                ('tipo_tela', models.CharField(blank=True, max_length=50, verbose_name='Tipo de Tela')),
                ('unidad_medida', models.CharField(choices=[('metro', 'Metro'), ('kg', 'Kilogramo'), ('unidad', 'Unidad'), ('rollo', 'Rollo')], default='metro', max_length=10, verbose_name='Unidad de Medida')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cantidad')),
                ('stock_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Stock Mínimo')),
                ('precio_costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio de Costo')),
                ('estado', models.CharField(choices=[('ACT', 'Activo'), ('BAJ', 'Baja')], default='ACT', max_length=3, verbose_name='Estado')),
                ('proveedor', models.CharField(blank=True, max_length=100, verbose_name='Proveedor')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Ingreso')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'ordering': ['tipo_material', 'articulo'],
            },
        ),
        migrations.CreateModel(
            name='PrendaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Código')),
                ('tipo', models.CharField(choices=[('venta', 'Para Venta'), ('alquiler', 'Para Alquiler')], max_length=10, verbose_name='Tipo')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='Modelo / Línea')),
                ('talla', models.CharField(blank=True, max_length=20, verbose_name='Talla')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Color')),
                ('codigo_referencia', models.CharField(blank=True, max_length=100, verbose_name='Código de Referencia')),
                ('condicion', models.CharField(blank=True, choices=[('nueva', 'Nueva'), ('usada', 'Usada'), ('remate', 'Remate')], default='nueva', help_text='Solo aplica a prendas de alquiler', max_length=10, verbose_name='Condición')),
                ('veces_alquilado', models.PositiveIntegerField(default=0, verbose_name='Veces Alquilado')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad en Stock')),
                ('stock_minimo', models.PositiveIntegerField(blank=True, null=True, verbose_name='Stock Mínimo')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Precio')),
                ('estado', models.CharField(choices=[('ACT', 'Activo'), ('BAJ', 'Baja')], default='ACT', max_length=3, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Ingreso')),
            ],
            options={
                'verbose_name': 'Prenda',
                'verbose_name_plural': 'Prendas',
                'ordering': ['nombre', 'talla'],
            },
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='misastreria.prendainventario', verbose_name='Artículo'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='misastreria.prendainventario', verbose_name='Artículo'),
        ),
        migrations.DeleteModel(
            name='BajaInventario',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
    ]
