# Generated by Django 5.2 on 2026-04-27 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misastreria', '0007_insumo_prendainventario_remove_inventario_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alquiler',
            name='articulo',
        ),
        migrations.RemoveField(
            model_name='alquiler',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='alquiler',
            name='costo_alquiler',
        ),
        migrations.AddField(
            model_name='alquiler',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento (%)'),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alquileres', to='misastreria.empleado', verbose_name='Empleado'),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='notas',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alquileres', to='misastreria.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Código'),
        ),
        migrations.CreateModel(
            name='AlquilerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal')),
                ('alquiler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='misastreria.alquiler')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='misastreria.prendainventario', verbose_name='Prenda')),
            ],
            options={
                'verbose_name': 'Ítem de Alquiler',
                'verbose_name_plural': 'Ítems de Alquiler',
            },
        ),
    ]
