# Generated by Django 5.2 on 2026-05-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misastreria', '0013_medidas_charfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confeccion',
            name='garantia',
        ),
        migrations.AddField(
            model_name='confeccion',
            name='garantia_hasta',
            field=models.DateField(blank=True, null=True, verbose_name='Garantía hasta'),
        ),
        migrations.AddField(
            model_name='confeccion',
            name='garantia_meses',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Garantía (meses)'),
        ),
        migrations.AlterField(
            model_name='estadoalquiler',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tipocontrato',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tipoprenda',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tiporeparacion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='unidadmedida',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
