# Generated by Django 5.2 on 2026-05-07 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misastreria', '0018_prendaitem_fecha_baja'),
    ]

    operations = [
        migrations.AddField(
            model_name='prendainventario',
            name='max_usos_default',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Máx. usos por defecto'),
        ),
        migrations.AddField(
            model_name='prendaitem',
            name='max_usos',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Máx. usos'),
        ),
        migrations.AlterField(
            model_name='alquileritem',
            name='prenda_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alquiler_items', to='misastreria.prendaitem', verbose_name='Item de Prenda'),
        ),
        migrations.AlterField(
            model_name='ventaitem',
            name='prenda_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='venta_items', to='misastreria.prendaitem', verbose_name='Item de Prenda'),
        ),
    ]
