# Generated by Django 5.2 on 2026-05-08 20:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misastreria', '0019_prendainventario_max_usos_default_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KardexEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('alquiler', 'Alquiler'), ('devolucion', 'Devolución'), ('venta', 'Venta'), ('baja', 'Baja')], max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('alquiler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kardex_eventos', to='misastreria.alquiler')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kardex_eventos', to='misastreria.cliente')),
                ('prenda_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kardex_eventos', to='misastreria.prendaitem')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kardex_eventos', to='misastreria.venta')),
            ],
            options={
                'verbose_name': 'Evento de Kardex',
                'verbose_name_plural': 'Eventos de Kardex',
                'ordering': ['timestamp', 'id'],
                'indexes': [models.Index(fields=['prenda_item', 'timestamp'], name='misastreria_prenda__3ab3ae_idx'), models.Index(fields=['timestamp'], name='misastreria_timesta_e99450_idx')],
            },
        ),
    ]
