# Generated by Django 5.2 on 2026-05-08 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misastreria', '0020_kardexevento'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproduccion',
            name='cantidad',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad a producir'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='prenda_inventario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_produccion', to='misastreria.prendainventario', verbose_name='Prenda destino (stock)'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='tipo',
            field=models.CharField(choices=[('cliente', 'Para cliente'), ('stock', 'Para inventario')], default='cliente', max_length=10, verbose_name='Tipo de orden'),
        ),
    ]
