# Generated by Django 5.2 on 2026-05-08 22:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misastreria', '0021_ordenproduccion_cantidad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Tipo de gasto',
                'verbose_name_plural': 'Tipos de gasto',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='alquiler',
            name='forma_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('qr', 'QR'), ('tarjeta', 'Tarjeta')], default='efectivo', max_length=15, verbose_name='Forma de Pago'),
        ),
        migrations.AddField(
            model_name='confeccion',
            name='forma_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('qr', 'QR'), ('tarjeta', 'Tarjeta')], default='efectivo', max_length=15, verbose_name='Forma de Pago'),
        ),
        migrations.AddField(
            model_name='reparacion',
            name='forma_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('qr', 'QR'), ('tarjeta', 'Tarjeta')], default='efectivo', max_length=15, verbose_name='Forma de Pago'),
        ),
        migrations.AddField(
            model_name='venta',
            name='forma_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('qr', 'QR'), ('tarjeta', 'Tarjeta')], default='efectivo', max_length=15, verbose_name='Forma de Pago'),
        ),
        migrations.CreateModel(
            name='CajaSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Apertura')),
                ('monto_apertura', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Monto de Apertura')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('monto_cierre_declarado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto Cierre Declarado')),
                ('monto_cierre_sistema', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto Cierre Sistema')),
                ('diferencia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Diferencia')),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=10, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('usuario_apertura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_abiertas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Apertura')),
                ('usuario_cierre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_cerradas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Cierre')),
            ],
            options={
                'verbose_name': 'Caja Sesión',
                'verbose_name_plural': 'Caja Sesiones',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='CajaMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Código')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=10, verbose_name='Tipo')),
                ('concepto', models.CharField(choices=[('alquiler_cobro', 'Cobro de alquiler'), ('venta_cobro', 'Cobro de venta'), ('confeccion_adelanto', 'Adelanto de confección'), ('confeccion_saldo', 'Saldo de confección'), ('reparacion_cobro', 'Cobro de reparación'), ('ingreso_manual', 'Ingreso manual'), ('apertura_caja', 'Apertura de caja'), ('sobrante_caja', 'Sobrante de caja'), ('gasto_fijo', 'Gasto fijo'), ('gasto_operativo', 'Gasto operativo'), ('retiro', 'Retiro del dueño'), ('devolucion_cliente', 'Devolución a cliente'), ('anulacion_cobro', 'Anulación de cobro'), ('faltante_caja', 'Faltante de caja'), ('gasto_varios', 'Gasto varios')], max_length=40, verbose_name='Concepto')),
                ('origen', models.CharField(choices=[('automatico', 'Automático'), ('manual', 'Manual')], default='manual', max_length=12, verbose_name='Origen')),
                ('forma_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('qr', 'QR'), ('tarjeta', 'Tarjeta'), ('cheque', 'Cheque'), ('mixto', 'Mixto')], default='efectivo', max_length=15, verbose_name='Forma de Pago')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caja_movimientos', to='misastreria.cliente', verbose_name='Cliente')),
                ('movimiento_reverso', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverso_de', to='misastreria.cajamovimiento', verbose_name='Movimiento Reverso')),
                ('referencia_alquiler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caja_movimientos', to='misastreria.alquiler', verbose_name='Alquiler')),
                ('referencia_confeccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caja_movimientos', to='misastreria.confeccion', verbose_name='Confección')),
                ('referencia_reparacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caja_movimientos', to='misastreria.reparacion', verbose_name='Reparación')),
                ('referencia_venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caja_movimientos', to='misastreria.venta', verbose_name='Venta')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('sesion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='misastreria.cajasesion', verbose_name='Sesión')),
                ('tipo_gasto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='misastreria.tipogasto', verbose_name='Tipo de Gasto')),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='cajasesion',
            index=models.Index(fields=['-fecha_apertura'], name='misastreria_fecha_a_b94f89_idx'),
        ),
        migrations.AddIndex(
            model_name='cajasesion',
            index=models.Index(fields=['estado'], name='misastreria_estado_0e3aaa_idx'),
        ),
        migrations.AddConstraint(
            model_name='cajasesion',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'abierta')), fields=('estado',), name='unique_caja_abierta'),
        ),
        migrations.AddIndex(
            model_name='cajamovimiento',
            index=models.Index(fields=['-fecha'], name='misastreria_fecha_ae3aae_idx'),
        ),
        migrations.AddIndex(
            model_name='cajamovimiento',
            index=models.Index(fields=['sesion', '-fecha'], name='misastreria_sesion__b396e4_idx'),
        ),
        migrations.AddIndex(
            model_name='cajamovimiento',
            index=models.Index(fields=['concepto', '-fecha'], name='misastreria_concept_cde8db_idx'),
        ),
        migrations.AddIndex(
            model_name='cajamovimiento',
            index=models.Index(fields=['forma_pago', '-fecha'], name='misastreria_forma_p_8c0993_idx'),
        ),
        migrations.AddIndex(
            model_name='cajamovimiento',
            index=models.Index(fields=['tipo', '-fecha'], name='misastreria_tipo_250a5f_idx'),
        ),
        migrations.AddConstraint(
            model_name='cajamovimiento',
            constraint=models.UniqueConstraint(condition=models.Q(('movimiento_reverso__isnull', True)), fields=('referencia_alquiler', 'concepto'), name='unique_mov_alquiler_activo'),
        ),
        migrations.AddConstraint(
            model_name='cajamovimiento',
            constraint=models.UniqueConstraint(condition=models.Q(('movimiento_reverso__isnull', True)), fields=('referencia_venta', 'concepto'), name='unique_mov_venta_activo'),
        ),
        migrations.AddConstraint(
            model_name='cajamovimiento',
            constraint=models.UniqueConstraint(condition=models.Q(('movimiento_reverso__isnull', True)), fields=('referencia_confeccion', 'concepto'), name='unique_mov_confeccion_activo'),
        ),
        migrations.AddConstraint(
            model_name='cajamovimiento',
            constraint=models.UniqueConstraint(condition=models.Q(('movimiento_reverso__isnull', True)), fields=('referencia_reparacion', 'concepto'), name='unique_mov_reparacion_activo'),
        ),
    ]
