# Generated by Django 5.2 on 2026-05-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misastreria', '0022_tipogasto_alquiler_forma_pago_confeccion_forma_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='garantia_monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto de Garantía'),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='garantia_tipo',
            field=models.CharField(blank=True, choices=[('', 'Sin garantía'), ('efectivo', 'Efectivo'), ('qr', 'QR'), ('transferencia', 'Transferencia'), ('descripcion', 'Descripción')], default='', max_length=15, verbose_name='Tipo de Garantía'),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='garantia',
            field=models.TextField(blank=True, verbose_name='Descripción de Garantía'),
        ),
    ]
