# Generated by Django 5.2 on 2026-05-20 10:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misastreria', '0023_alquiler_garantia_monto_alquiler_garantia_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('precio_sugerido', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio sugerido')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Conjunto',
                'verbose_name_plural': 'Conjuntos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='prendainventario',
            name='tipo_prenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prendas_inventario', to='misastreria.tipoprenda', verbose_name='Tipo de Prenda'),
        ),
        migrations.AlterField(
            model_name='cajamovimiento',
            name='concepto',
            field=models.CharField(choices=[('alquiler_cobro', 'Cobro de alquiler'), ('garantia_alquiler', 'Garantía de alquiler'), ('garantia_devolucion', 'Devolución de garantía'), ('venta_cobro', 'Cobro de venta'), ('confeccion_adelanto', 'Adelanto de confección'), ('confeccion_saldo', 'Saldo de confección'), ('reparacion_cobro', 'Cobro de reparación'), ('ingreso_manual', 'Ingreso manual'), ('egreso_manual', 'Egreso manual'), ('apertura_caja', 'Apertura de caja'), ('sobrante_caja', 'Sobrante de caja'), ('gasto_fijo', 'Gasto fijo'), ('gasto_operativo', 'Gasto operativo'), ('retiro', 'Retiro del dueño'), ('devolucion_cliente', 'Devolución a cliente'), ('anulacion_cobro', 'Anulación de cobro'), ('faltante_caja', 'Faltante de caja'), ('gasto_varios', 'Gasto varios')], max_length=40, verbose_name='Concepto'),
        ),
        migrations.CreateModel(
            name='ConjuntoSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcional', models.BooleanField(default=False, verbose_name='Opcional')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('conjunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='misastreria.conjunto')),
                ('tipo_prenda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='misastreria.tipoprenda', verbose_name='Tipo de prenda')),
            ],
            options={
                'verbose_name': 'Slot de conjunto',
                'verbose_name_plural': 'Slots de conjunto',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
