# Generated by Django 5.2 on 2026-05-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misastreria', '0024_conjunto_prendainventario_tipo_prenda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquileritem',
            name='grupo_conjunto',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='ventaitem',
            name='grupo_conjunto',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
