# Generated by Django 5.2 on 2026-05-20 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misastreria', '0025_add_grupo_conjunto_alquiler_venta_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conjuntoslot',
            name='tipo_prenda',
        ),
        migrations.AddField(
            model_name='conjuntoslot',
            name='prenda_inventario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conjunto_slots', to='misastreria.prendainventario', verbose_name='Prenda'),
        ),
    ]
