# Generated by Django 5.2 on 2026-05-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misastreria', '0026_swap_conjuntoslot_tipo_prenda_to_prenda_inventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=100, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='apellido_paterno',
            field=models.CharField(blank=True, max_length=100, verbose_name='Apellido Paterno'),
        ),
    ]
