# Generated by Django 5.2 on 2026-05-26 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misastreria', '0031_conjuntoslot_prenda_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='conjunto',
            name='tipo',
            field=models.CharField(choices=[('alquiler', 'Alquiler'), ('venta', 'Venta')], default='alquiler', max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='cajamovimiento',
            name='concepto',
            field=models.CharField(choices=[('alquiler_cobro', 'Cobro de alquiler'), ('alquiler_pago', 'Pago de alquiler'), ('garantia_alquiler', 'Garantía de alquiler'), ('garantia_devolucion', 'Devolución de garantía'), ('venta_cobro', 'Cobro de venta'), ('confeccion_adelanto', 'Adelanto de confección'), ('confeccion_saldo', 'Saldo de confección'), ('confeccion_pago', 'Pago de confección'), ('reparacion_cobro', 'Cobro de reparación'), ('reparacion_pago', 'Pago de reparación'), ('reparacion_saldo', 'Saldo de reparación'), ('ingreso_manual', 'Ingreso manual'), ('egreso_manual', 'Egreso manual'), ('apertura_caja', 'Apertura de caja'), ('sobrante_caja', 'Sobrante de caja'), ('gasto_fijo', 'Gasto fijo'), ('gasto_operativo', 'Gasto operativo'), ('retiro', 'Retiro del dueño'), ('devolucion_cliente', 'Devolución a cliente'), ('anulacion_cobro', 'Anulación de cobro'), ('faltante_caja', 'Faltante de caja'), ('gasto_varios', 'Gasto varios')], max_length=40, verbose_name='Concepto'),
        ),
    ]
