# Generated by Django 5.2 on 2026-05-26 06:24

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misastreria', '0035_ubicacion_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquileritem',
            name='precio_reparacion',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Precio Arreglo'),
        ),
        migrations.AddField(
            model_name='alquileritem',
            name='tipo_reparacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='misastreria.tiporeparacion', verbose_name='Tipo de Arreglo'),
        ),
        migrations.AddField(
            model_name='ventaitem',
            name='precio_reparacion',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Precio Arreglo'),
        ),
        migrations.AddField(
            model_name='ventaitem',
            name='tipo_reparacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='misastreria.tiporeparacion', verbose_name='Tipo de Arreglo'),
        ),
        migrations.AlterField(
            model_name='prendaitem',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('alquilado', 'Alquilado'), ('reservado', 'Reservado'), ('baja', 'Baja')], default='disponible', max_length=12, verbose_name='Estado'),
        ),
    ]
