# Generated by Django 5.2 on 2026-05-26 06:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misastreria', '0036_alquileritem_precio_reparacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='confeccion',
            name='porcentaje_comision',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Comisión del empleado sobre el precio. Solo aplica si la confección está entregada.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Porcentaje Comisión (%)'),
        ),
        migrations.AddField(
            model_name='reparacion',
            name='porcentaje_comision',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Comisión del empleado sobre el total. Solo aplica si la reparación está entregada.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Porcentaje Comisión (%)'),
        ),
        migrations.AlterField(
            model_name='cajamovimiento',
            name='concepto',
            field=models.CharField(choices=[('alquiler_cobro', 'Cobro de alquiler'), ('alquiler_pago', 'Pago de alquiler'), ('garantia_alquiler', 'Garantía de alquiler'), ('garantia_devolucion', 'Devolución de garantía'), ('venta_cobro', 'Cobro de venta'), ('confeccion_adelanto', 'Adelanto de confección'), ('confeccion_saldo', 'Saldo de confección'), ('confeccion_pago', 'Pago de confección'), ('reparacion_cobro', 'Cobro de reparación'), ('reparacion_pago', 'Pago de reparación'), ('reparacion_saldo', 'Saldo de reparación'), ('ingreso_manual', 'Ingreso manual'), ('egreso_manual', 'Egreso manual'), ('apertura_caja', 'Apertura de caja'), ('sobrante_caja', 'Sobrante de caja'), ('gasto_fijo', 'Gasto fijo'), ('gasto_operativo', 'Gasto operativo'), ('retiro', 'Retiro del dueño'), ('devolucion_cliente', 'Devolución a cliente'), ('anulacion_cobro', 'Anulación de cobro'), ('faltante_caja', 'Faltante de caja'), ('gasto_varios', 'Gasto varios'), ('comision_empleado', 'Comisión de empleado')], max_length=40, verbose_name='Concepto'),
        ),
        migrations.AlterField(
            model_name='confeccion',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confecciones', to='misastreria.empleado'),
        ),
        migrations.CreateModel(
            name='PagoComisionEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Código')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('via_caja', models.BooleanField(default=True, help_text='Si está activo, crea un egreso en caja. Si no, registra el pago sin afectar caja.', verbose_name='Vía caja')),
                ('forma_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('qr', 'QR'), ('tarjeta', 'Tarjeta')], default='efectivo', max_length=15, verbose_name='Forma de Pago')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_comision', to='misastreria.empleado', verbose_name='Empleado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Pago de Comisión',
                'verbose_name_plural': 'Pagos de Comisión',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AddField(
            model_name='cajamovimiento',
            name='referencia_pago_comision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caja_movimientos', to='misastreria.pagocomisionempleado', verbose_name='Pago de Comisión'),
        ),
        migrations.AddConstraint(
            model_name='cajamovimiento',
            constraint=models.UniqueConstraint(condition=models.Q(('movimiento_reverso__isnull', True)), fields=('referencia_pago_comision', 'concepto'), name='unique_mov_comision_activo'),
        ),
    ]
