# Generated by Django 5.2 on 2026-05-26 06:59

from django.db import migrations, models


def populate_from_existing(apps, schema_editor):
    ModeloConfeccion = apps.get_model('misastreria', 'ModeloConfeccion')
    Confeccion = apps.get_model('misastreria', 'Confeccion')
    nombres = set(
        v for v in Confeccion.objects.values_list('modelo', flat=True).distinct()
        if v and v.strip()
    )
    for nombre in sorted(nombres):
        ModeloConfeccion.objects.get_or_create(nombre=nombre.strip())


class Migration(migrations.Migration):

    dependencies = [
        ('misastreria', '0037_comisiones_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloConfeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Modelo de Confección',
                'verbose_name_plural': 'Modelos de Confección',
                'ordering': ['nombre'],
            },
        ),
        migrations.RunPython(populate_from_existing, migrations.RunPython.noop),
    ]
