# Generated by Django 5.2 on 2026-05-27 15:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misastreria', '0038_modelo_confeccion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cajamovimiento',
            name='unique_mov_reparacion_activo',
        ),
        migrations.AddConstraint(
            model_name='cajamovimiento',
            constraint=models.UniqueConstraint(condition=models.Q(('movimiento_reverso__isnull', True), models.Q(('concepto', 'reparacion_pago'), _negated=True)), fields=('referencia_reparacion', 'concepto'), name='unique_mov_reparacion_activo'),
        ),
    ]
