# Generated by Django 5.2 on 2026-05-27 17:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misastreria', '0039_fix_unique_mov_reparacion_pagos'),
    ]

    operations = [
        migrations.AddField(
            model_name='prendainventario',
            name='precio_alquiler_base',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio de alquiler cuando la prenda es nueva. Si no se define, no se sugiere precio.', max_digits=10, null=True, verbose_name='Precio alquiler base'),
        ),
        migrations.AddField(
            model_name='prendainventario',
            name='precio_alquiler_minimo_pct',
            field=models.PositiveSmallIntegerField(default=20, help_text='Porcentaje mínimo del precio base al que puede llegar. Default: 20%', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Precio mínimo (%)'),
        ),
    ]
