# Generated by Django 5.2 on 2026-05-27 21:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misastreria', '0040_add_precio_alquiler_base'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cajamovimiento',
            name='unique_mov_venta_activo',
        ),
        migrations.RemoveConstraint(
            model_name='cajamovimiento',
            name='unique_mov_alquiler_activo',
        ),
        migrations.RemoveConstraint(
            model_name='cajamovimiento',
            name='unique_mov_confeccion_activo',
        ),
        migrations.RemoveConstraint(
            model_name='cajamovimiento',
            name='unique_mov_reparacion_activo',
        ),
        migrations.AddConstraint(
            model_name='cajamovimiento',
            constraint=models.UniqueConstraint(condition=models.Q(('movimiento_reverso__isnull', True), models.Q(('concepto__in', ['alquiler_pago', 'anulacion_cobro']), _negated=True)), fields=('referencia_alquiler', 'concepto'), name='unique_mov_alquiler_activo'),
        ),
        migrations.AddConstraint(
            model_name='cajamovimiento',
            constraint=models.UniqueConstraint(condition=models.Q(('movimiento_reverso__isnull', True), models.Q(('concepto', 'anulacion_cobro'), _negated=True)), fields=('referencia_venta', 'concepto'), name='unique_mov_venta_activo'),
        ),
        migrations.AddConstraint(
            model_name='cajamovimiento',
            constraint=models.UniqueConstraint(condition=models.Q(('movimiento_reverso__isnull', True), models.Q(('concepto__in', ['confeccion_pago', 'anulacion_cobro']), _negated=True)), fields=('referencia_confeccion', 'concepto'), name='unique_mov_confeccion_activo'),
        ),
        migrations.AddConstraint(
            model_name='cajamovimiento',
            constraint=models.UniqueConstraint(condition=models.Q(('movimiento_reverso__isnull', True), models.Q(('concepto__in', ['reparacion_pago', 'anulacion_cobro']), _negated=True)), fields=('referencia_reparacion', 'concepto'), name='unique_mov_reparacion_activo'),
        ),
    ]
