# Generated by Django 5.2 on 2026-05-27 21:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misastreria', '0041_fix_unique_mov_anulacion_cobro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cajamovimiento',
            name='unique_mov_alquiler_activo',
        ),
        migrations.RemoveConstraint(
            model_name='cajamovimiento',
            name='unique_mov_venta_activo',
        ),
        migrations.RemoveConstraint(
            model_name='cajamovimiento',
            name='unique_mov_reparacion_activo',
        ),
        migrations.AlterField(
            model_name='cajamovimiento',
            name='concepto',
            field=models.CharField(choices=[('alquiler_cobro', 'Cobro de alquiler'), ('alquiler_pago', 'Pago de alquiler'), ('alquiler_ajuste', 'Ajuste de alquiler'), ('garantia_alquiler', 'Garantía de alquiler'), ('garantia_devolucion', 'Devolución de garantía'), ('venta_cobro', 'Cobro de venta'), ('venta_ajuste', 'Ajuste de venta'), ('confeccion_adelanto', 'Adelanto de confección'), ('confeccion_saldo', 'Saldo de confección'), ('confeccion_pago', 'Pago de confección'), ('reparacion_cobro', 'Cobro de reparación'), ('reparacion_pago', 'Pago de reparación'), ('reparacion_saldo', 'Saldo de reparación'), ('reparacion_ajuste', 'Ajuste de reparación'), ('ingreso_manual', 'Ingreso manual'), ('egreso_manual', 'Egreso manual'), ('apertura_caja', 'Apertura de caja'), ('sobrante_caja', 'Sobrante de caja'), ('gasto_fijo', 'Gasto fijo'), ('gasto_operativo', 'Gasto operativo'), ('retiro', 'Retiro del dueño'), ('devolucion_cliente', 'Devolución a cliente'), ('anulacion_cobro', 'Anulación de cobro'), ('faltante_caja', 'Faltante de caja'), ('gasto_varios', 'Gasto varios'), ('comision_empleado', 'Comisión de empleado')], max_length=40, verbose_name='Concepto'),
        ),
        migrations.AddConstraint(
            model_name='cajamovimiento',
            constraint=models.UniqueConstraint(condition=models.Q(('movimiento_reverso__isnull', True), models.Q(('concepto__in', ['alquiler_pago', 'alquiler_ajuste', 'anulacion_cobro']), _negated=True)), fields=('referencia_alquiler', 'concepto'), name='unique_mov_alquiler_activo'),
        ),
        migrations.AddConstraint(
            model_name='cajamovimiento',
            constraint=models.UniqueConstraint(condition=models.Q(('movimiento_reverso__isnull', True), models.Q(('concepto__in', ['venta_ajuste', 'anulacion_cobro']), _negated=True)), fields=('referencia_venta', 'concepto'), name='unique_mov_venta_activo'),
        ),
        migrations.AddConstraint(
            model_name='cajamovimiento',
            constraint=models.UniqueConstraint(condition=models.Q(('movimiento_reverso__isnull', True), models.Q(('concepto__in', ['reparacion_pago', 'reparacion_ajuste', 'anulacion_cobro']), _negated=True)), fields=('referencia_reparacion', 'concepto'), name='unique_mov_reparacion_activo'),
        ),
    ]
