# Generated by Django 5.2 on 2026-05-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misastreria', '0043_seed_catalog_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='pais',
            field=models.CharField(blank=True, max_length=100, verbose_name='País'),
        ),
    ]
