# Generated by Django 5.2 on 2026-05-29 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misastreria', '0045_remove_cajamovimiento_unique_mov_venta_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajamovimiento',
            name='via_caja',
            field=models.BooleanField(default=True, help_text='Si está desactivado, el pago queda en reserva y no afecta el saldo de caja.', verbose_name='Registrar en caja'),
        ),
    ]
