# Generated by Django 5.2 on 2026-05-29 06:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misastreria', '0046_cajamovimiento_via_caja'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfeccionEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_comision', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Porcentaje Comisión (%)')),
                ('confeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='misastreria.confeccion', verbose_name='Confección')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_confeccion', to='misastreria.empleado', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Asignación de confección',
                'verbose_name_plural': 'Asignaciones de confección',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('confeccion', 'empleado'), name='unique_empleado_confeccion')],
            },
        ),
        migrations.CreateModel(
            name='ReparacionEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_comision', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Porcentaje Comisión (%)')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_reparacion', to='misastreria.empleado', verbose_name='Empleado')),
                ('reparacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='misastreria.reparacion', verbose_name='Reparación')),
            ],
            options={
                'verbose_name': 'Asignación de reparación',
                'verbose_name_plural': 'Asignaciones de reparación',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('reparacion', 'empleado'), name='unique_empleado_reparacion')],
            },
        ),
    ]
