# Generated by Django 5.2 on 2026-05-30 22:41

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misastreria', '0048_migrar_empleado_a_asignaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquileritem',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arreglos_alquiler', to='misastreria.empleado', verbose_name='Empleado del arreglo'),
        ),
        migrations.AddField(
            model_name='alquileritem',
            name='porcentaje_comision',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Comisión del empleado sobre el precio del arreglo. Se devenga cuando el alquiler está devuelto.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Porcentaje Comisión (%)'),
        ),
        migrations.AddField(
            model_name='ventaitem',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arreglos_venta', to='misastreria.empleado', verbose_name='Empleado del arreglo'),
        ),
        migrations.AddField(
            model_name='ventaitem',
            name='porcentaje_comision',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Comisión del empleado sobre el precio del arreglo. Se devenga cuando la venta está efectuada.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Porcentaje Comisión (%)'),
        ),
    ]
