# Generated by Django 5.2 on 2026-06-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misastreria', '0049_alquileritem_empleado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='confeccionitem',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio de esta prenda confeccionada.', max_digits=10, null=True, verbose_name='Costo'),
        ),
    ]
