# Generated by Django 5.2 on 2026-06-17 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misastreria', '0052_orden_produccion_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cajamovimiento',
            name='concepto',
            field=models.CharField(choices=[('alquiler_cobro', 'Cobro de alquiler'), ('alquiler_pago', 'Pago de alquiler'), ('alquiler_ajuste', 'Ajuste de alquiler'), ('alquiler_recargo', 'Recargo de alquiler'), ('garantia_alquiler', 'Garantía de alquiler'), ('garantia_devolucion', 'Devolución de garantía'), ('venta_cobro', 'Cobro de venta'), ('venta_ajuste', 'Ajuste de venta'), ('venta_adelanto', 'Adelanto de venta'), ('venta_pago', 'Pago de venta'), ('venta_saldo', 'Saldo de venta'), ('confeccion_adelanto', 'Adelanto de confección'), ('confeccion_saldo', 'Saldo de confección'), ('confeccion_pago', 'Pago de confección'), ('reparacion_cobro', 'Cobro de reparación'), ('reparacion_pago', 'Pago de reparación'), ('reparacion_saldo', 'Saldo de reparación'), ('reparacion_ajuste', 'Ajuste de reparación'), ('ingreso_manual', 'Ingreso manual'), ('egreso_manual', 'Egreso manual'), ('apertura_caja', 'Apertura de caja'), ('sobrante_caja', 'Sobrante de caja'), ('gasto_fijo', 'Gasto fijo'), ('gasto_operativo', 'Gasto operativo'), ('retiro', 'Retiro del dueño'), ('devolucion_cliente', 'Devolución a cliente'), ('anulacion_cobro', 'Anulación de cobro'), ('faltante_caja', 'Faltante de caja'), ('gasto_varios', 'Gasto varios'), ('comision_empleado', 'Comisión de empleado')], max_length=40, verbose_name='Concepto'),
        ),
    ]
