# Generated by Django 5.2 on 2026-08-16 23:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misastreria', '0055_plantilla_etiqueta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionImpresora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oscuridad', models.SmallIntegerField(default=0, help_text='De -30 a 30, relativo al ajuste de la impresora. Si las letras salen débiles, subilo de a 4 y volvé a probar.', validators=[django.core.validators.MinValueValidator(-30), django.core.validators.MaxValueValidator(30)], verbose_name='Ajuste de oscuridad')),
                ('velocidad', models.PositiveSmallIntegerField(default=4, help_text='De 2 a 6. Más lento imprime más marcado.', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(6)], verbose_name='Velocidad (pulgadas por segundo)')),
                ('usa_ribbon', models.BooleanField(default=True, help_text='Desmarcá sólo si el rollo es térmico directo y no lleva cinta.', verbose_name='Usa cinta (transferencia térmica)')),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Impresora',
                'verbose_name_plural': 'Configuración de Impresora',
            },
        ),
    ]
