# Generated by Django 5.2 on 2026-08-17 01:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misastreria', '0056_configuracionimpresora'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionimpresora',
            name='desplazamiento_x',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Positivo mueve el diseño a la derecha; negativo, a la izquierda.', max_digits=4, validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(20)], verbose_name='Corrimiento horizontal (mm)'),
        ),
        migrations.AddField(
            model_name='configuracionimpresora',
            name='desplazamiento_y',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Positivo baja el diseño; negativo lo sube.', max_digits=4, validators=[django.core.validators.MinValueValidator(-20), django.core.validators.MaxValueValidator(20)], verbose_name='Corrimiento vertical (mm)'),
        ),
        migrations.AddField(
            model_name='configuracionimpresora',
            name='tipo_papel',
            field=models.CharField(blank=True, choices=[('', 'No tocar (usar lo que tiene la impresora)'), ('gap', 'Etiquetas separadas, con espacio entre una y otra'), ('continuo', 'Papel continuo, sin cortes'), ('marca', 'Con marca negra en el reverso')], default='', help_text='Sólo cambialo si la impresora no encuentra dónde termina cada etiqueta.', max_length=10, verbose_name='Tipo de papel'),
        ),
    ]
