# Generated by Django 5.2 on 2026-08-25 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misastreria', '0058_plantillas_codigo_barra'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantillaetiqueta',
            name='orientacion',
            field=models.CharField(choices=[('normal', 'Normal'), ('girada', 'Girada 90°')], default='normal', help_text='Girada apoya el diseño de costado sobre el mismo rollo: el papel no cambia, el texto sale leyéndose a lo largo de la etiqueta.', max_length=10, verbose_name='Orientación del contenido'),
        ),
    ]
