# Generated by Django 5.2 on 2026-09-11 02:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misastreria', '0061_alquiler_fecha_devolucion_real'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlquilerItemEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_comision_fijo', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Monto fijo en Bs que gana el empleado por este arreglo.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Comisión (Bs)')),
                ('alquiler_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='misastreria.alquileritem', verbose_name='Ítem')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_alquiler', to='misastreria.empleado', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Asignación de arreglo (alquiler)',
                'verbose_name_plural': 'Asignaciones de arreglo (alquiler)',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('alquiler_item', 'empleado'), name='unique_empleado_alquiler_item')],
            },
        ),
        migrations.CreateModel(
            name='VentaItemEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_comision_fijo', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Monto fijo en Bs que gana el empleado por este arreglo.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Comisión (Bs)')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_venta', to='misastreria.empleado', verbose_name='Empleado')),
                ('venta_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='misastreria.ventaitem', verbose_name='Ítem')),
            ],
            options={
                'verbose_name': 'Asignación de arreglo (venta)',
                'verbose_name_plural': 'Asignaciones de arreglo (venta)',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('venta_item', 'empleado'), name='unique_empleado_venta_item')],
            },
        ),
    ]
