# Generated by Django 5.2 on 2026-09-19 17:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misastreria', '0063_migrar_empleado_de_arreglos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, help_text='Auto-generado: C-001', max_length=20, unique=True, verbose_name='Número')),
                ('sigla', models.CharField(blank=True, help_text='Alias corto opcional, ej. AZUL-LANA', max_length=12, verbose_name='Sigla')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('tela', models.CharField(blank=True, max_length=100, verbose_name='Tela / color')),
                ('nota', models.TextField(blank=True, verbose_name='Nota')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Corte',
                'verbose_name_plural': 'Cortes',
                'ordering': ['-creado'],
            },
        ),
        migrations.AddField(
            model_name='prendaitem',
            name='corte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='misastreria.corte', verbose_name='Corte'),
        ),
    ]
