# Generated by Django 5.2 on 2026-09-19 18:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misastreria', '0064_corte'),
    ]

    operations = [
        migrations.CreateModel(
            name='AplicacionPagoComision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto aplicado')),
                ('detalle_snapshot', models.CharField(blank=True, help_text='Descripción de la devengación al momento del pago, para el historial si la fila original se borra más adelante.', max_length=200, verbose_name='Detalle')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('alquiler_item_empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aplicaciones_pago', to='misastreria.alquileritemempleado', verbose_name='Asignación de arreglo (alquiler)')),
                ('confeccion_empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aplicaciones_pago', to='misastreria.confeccionempleado', verbose_name='Asignación de confección')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='misastreria.pagocomisionempleado', verbose_name='Pago')),
                ('produccion_empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aplicaciones_pago', to='misastreria.ordenproduccionempleado', verbose_name='Asignación de producción')),
                ('reparacion_empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aplicaciones_pago', to='misastreria.reparacionempleado', verbose_name='Asignación de reparación')),
                ('venta_item_empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aplicaciones_pago', to='misastreria.ventaitemempleado', verbose_name='Asignación de arreglo (venta)')),
            ],
            options={
                'verbose_name': 'Aplicación de pago de comisión',
                'verbose_name_plural': 'Aplicaciones de pago de comisión',
                'ordering': ['id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('reparacion_empleado__isnull', True), ('confeccion_empleado__isnull', True), _connector='OR'), models.Q(('reparacion_empleado__isnull', True), ('venta_item_empleado__isnull', True), _connector='OR'), models.Q(('reparacion_empleado__isnull', True), ('alquiler_item_empleado__isnull', True), _connector='OR'), models.Q(('reparacion_empleado__isnull', True), ('produccion_empleado__isnull', True), _connector='OR'), models.Q(('confeccion_empleado__isnull', True), ('venta_item_empleado__isnull', True), _connector='OR'), models.Q(('confeccion_empleado__isnull', True), ('alquiler_item_empleado__isnull', True), _connector='OR'), models.Q(('confeccion_empleado__isnull', True), ('produccion_empleado__isnull', True), _connector='OR'), models.Q(('venta_item_empleado__isnull', True), ('alquiler_item_empleado__isnull', True), _connector='OR'), models.Q(('venta_item_empleado__isnull', True), ('produccion_empleado__isnull', True), _connector='OR'), models.Q(('alquiler_item_empleado__isnull', True), ('produccion_empleado__isnull', True), _connector='OR')), name='aplicacion_pago_comision_a_lo_sumo_una_asignacion')],
            },
        ),
    ]
