# Generated by Django 5.2 on 2026-09-19 19:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misastreria', '0066_backfill_aplicaciones_pago_comision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='fecha_alquiler',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de Alquiler'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_registro',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='confeccion',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='corte',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha_venta',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de Venta'),
        ),
    ]
