# Generated by Django 5.2 on 2026-09-25 01:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misastreria', '0067_fechas_default_localdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionimpresora',
            name='margen_arriba',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Cinta en blanco que se agrega arriba de cada etiqueta, para cortar y coser sin tocar el título.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)], verbose_name='Cinta extra arriba (mm)'),
        ),
    ]
