# Generated by Django 5.2 on 2026-09-28 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misastreria', '0068_configuracionimpresora_margen_arriba'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleado', to=settings.AUTH_USER_MODEL, verbose_name='Usuario del sistema'),
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_hash', models.CharField(blank=True, default='', max_length=128, verbose_name='Hash del PIN')),
                ('pin_intentos_fallidos', models.PositiveSmallIntegerField(default=0, verbose_name='Intentos fallidos de PIN')),
                ('pin_bloqueado', models.BooleanField(default=False, verbose_name='PIN bloqueado')),
                ('pin_actualizado', models.DateTimeField(blank=True, null=True, verbose_name='PIN actualizado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
                'permissions': [('acceder_sistema', 'Puede acceder al sistema'), ('registrar_cobro', 'Puede registrar cobros'), ('cambiar_estado_taller', 'Puede cambiar estados de taller (en proceso/entregado)'), ('abrir_caja', 'Puede abrir una sesión de caja'), ('operar_caja', 'Puede operar su propia sesión de caja'), ('supervisar_caja', 'Puede supervisar todas las sesiones de caja'), ('ver_reportes_caja', 'Puede ver reportes de caja'), ('ver_reportes', 'Puede ver reportes generales'), ('ver_analitica', 'Puede ver analítica'), ('imprimir_etiquetas', 'Puede imprimir etiquetas'), ('configurar_etiquetas', 'Puede configurar diseño/calibración de impresora de etiquetas'), ('gestionar_usuarios', 'Puede gestionar usuarios del sistema')],
            },
        ),
    ]
